plugins:
  - jekyll-sitemap
theme: jekyll-theme-minimal

title: "Lazuly's Page"
description: "ロボコンオタクのポートフォリオページ。"
logo: /img/icon_nhk2023.png
google_analytics: G-PN04M09J2X

twitter:
  username: lazuly_tech

